# -*- coding: utf-8 -*-
"""23174600151_nguyenvannam

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nf3wnRpWKu2Gzvns-XcsNXTePnTutvzc
"""

import sqlite3
import pandas as pd

# Tạo database trong RAM
conn = sqlite3.connect(":memory:")
cur = conn.cursor()

# Tạo bảng
cur.execute("""
CREATE TABLE student (
    student_id INTEGER,
    name TEXT,
    class TEXT,
    course_id INTEGER,
    score REAL
)
""")

cur.execute("""
CREATE TABLE course (
    id INTEGER,
    course_name TEXT
)
""")

# Chèn dữ liệu student đúng như đề
student_data = [
    (1, 'Nguyen Minh Hoang', 'May Tinh', 12, 6.7),
    (2, 'Tran Thi Lan', 'Kinh Te', 34, 9.2),
    (3, 'Pham Van Nam', 'Toan Tin', None, 7.9),
    (4, 'Le Thanh Huyen', 'Toan Tin', 20, 7.2),
    (5, 'Vu Quoc Anh', 'May Tinh', 24, 8.0),
    (6, 'Dang Thuy Linh', 'May Tinh', 24, 5.5),
    (7, 'Bui Tien Dung', 'Kinh Te', 34, 9.2),
    (8, 'Ho Ngoc Mai', 'Toan Tin', 20, 8.8),
    (9, 'Duong Huu Phuc', 'Kinh Te', None, 7.2),
    (10, 'Cao Thi Hanh', 'May Tinh', None, 7.0)
]

course_data = [
    (12, 'Giai tich'),
    (34, 'Thong ke'),
    (26, 'Tin hoc')
]

cur.executemany("INSERT INTO student VALUES (?, ?, ?, ?, ?)", student_data)
cur.executemany("INSERT INTO course VALUES (?, ?)", course_data)
conn.commit()

# Kiểm tra dữ liệu gốc
print("Bảng student:")
display(pd.read_sql_query("SELECT * FROM student", conn))

print("Bảng course:")
display(pd.read_sql_query("SELECT * FROM course", conn))



"""### 1. Tích Decartes (Cartesian Product)"""

print('Tích Decartes (Cartesian Product):')
display(pd.read_sql_query("SELECT * FROM student, course", conn))

# Kết nối 2 bảng
 sql_cartesian = """
SELECT *
FROM student s
CROSS JOIN course c
"""
df_cartesian = pd.read_sql_query(sql_cartesian, conn)
display(df_cartesian)
print("Số dòng của tích Descartes:", len(df_cartesian))

"""### Nhận xét chi tiết về Output của Tích Descartes

Dựa trực tiếp vào bảng kết quả vừa chạy, chúng ta có thể thấy những điểm đáng chú ý sau:

1. **Sự bùng nổ số lượng dòng (Output Size)**:
    - Dù bảng `student` chỉ có 10 người và `course` chỉ có 3 môn, nhưng output hiển thị tới **30 dòng**.
    - **Giải thích**: SQL lấy dòng 1 của student ghép lần lượt với 3 dòng của course, rồi đến dòng 2 của student cũng ghép với 3 dòng của course... cứ thế cho đến hết.

2. **Sự sai lệch về logic đăng ký (Logic Mismatch)**:
    - Quan sát dòng 0, 1, 2: Sinh viên **Nguyen Minh Hoang** có `course_id` là **12**, nhưng output lại hiện ra cả 3 dòng ghép anh này với môn 12, 34 và 26.
    - **Hệ quả**: Chỉ có dòng 0 là đúng thực tế, dòng 1 và 2 là dữ liệu 'rác' do phép nhân tập hợp tạo ra.

3. **Xử lý các dòng có giá trị NULL**:
    - Quan sát sinh viên **Pham Van Nam** (không có `course_id` - NaN): Trong output, anh này vẫn bị ép phải ghép cặp với cả 3 môn học.
    - Điều này chứng minh Tích Descartes **bỏ qua hoàn toàn** các mối quan hệ về khóa ngoại (Foreign Key).

4. **Kết luận từ Output**:
    - Output này cho thấy một cái nhìn toàn diện về **tất cả các khả năng kết hợp có thể xảy ra**.
    - Nó cực kỳ hữu ích khi bạn muốn tạo ra một danh mục kiểm tra (checklist) trống (ví dụ: tạo danh sách cho tất cả sinh viên đi thi tất cả các môn), nhưng nó **không dùng được** để xem sinh viên thực tế đang học môn nào.

### 2. INNER JOIN (Kết nối nội)

Phép toán này chỉ trả về những dòng có sự trùng khớp khóa giữa hai bảng. Những sinh viên chưa đăng ký môn (NULL) hoặc những môn chưa có sinh viên đăng ký sẽ bị loại bỏ.
"""

sql_inner = """
SELECT
    s.student_id,
    s.name,
    s.course_id,
    c.course_name
FROM student s
INNER JOIN course c ON s.course_id = c.id
"""
df_inner = pd.read_sql_query(sql_inner, conn)
display(df_inner)
print(f"Số dòng thu được: {len(df_inner)}")

"""**Nhận xét INNER JOIN:**
- **Kết quả**: Chỉ có 3 dòng.
- **Lý do**: Chỉ có 3 sinh viên (Hoàng, Lan, Dũng) có `course_id` khớp với bảng `course`.
- **Mất mát dữ liệu**: Các sinh viên như 'Pham Van Nam' (course_id NULL) và môn 'Tin hoc' (không ai học) đều biến mất khỏi kết quả.

### 3. LEFT JOIN (Kết nối trái)

Giữ lại toàn bộ danh sách sinh viên ở bảng bên trái. Nếu sinh viên nào không có môn học tương ứng, các cột từ bảng `course` sẽ hiển thị `None` (NULL).
"""

sql_left = """
SELECT
    s.student_id,
    s.name,
    s.course_id,
    c.course_name
FROM student s
LEFT JOIN course c ON s.course_id = c.id
"""
df_left = pd.read_sql_query(sql_left, conn)
display(df_left)
print(f"Số dòng thu được: {len(df_left)}")

"""**Nhận xét LEFT JOIN:**
- **Kết quả**: 10 dòng (bằng đúng số lượng sinh viên).
- **Ưu điểm**: Đảm bảo không bỏ sót bất kỳ sinh viên nào. Những người như 'Pham Van Nam' hoặc 'Cao Thi Hanh' vẫn xuất hiện với `course_name` là `None`.

### 4. RIGHT JOIN (Kết nối phải - Mô phỏng)

Vì SQLite không hỗ trợ `RIGHT JOIN`, ta mô phỏng bằng cách đổi vị trí hai bảng và dùng `LEFT JOIN`. Mục tiêu là lấy toàn bộ danh mục môn học.
"""

sql_right = """
SELECT
    s.student_id,
    s.name,
    c.id AS course_id,
    c.course_name
FROM course c
LEFT JOIN student s ON c.id = s.course_id
"""
df_right = pd.read_sql_query(sql_right, conn)
display(df_right)
print(f"Số dòng thu được: {len(df_right)}")

"""**Nhận xét RIGHT JOIN:**
- **Kết quả**: Tập trung vào bảng `course`.
- **Điểm đặc biệt**: Môn 'Tin hoc' (ID 26) xuất hiện dù không có sinh viên nào đăng ký. Ngược lại, những sinh viên chưa có môn học sẽ bị loại khỏi bảng này.

### 5. FULL OUTER JOIN (Kết nối toàn phần - Mô phỏng)

Lấy tất cả sinh viên và tất cả môn học. SQLite mô phỏng bằng cách `UNION` kết quả của LEFT JOIN và một phần của RIGHT JOIN.
"""

sql_full = """
-- Lấy tất cả sinh viên (LEFT JOIN)
SELECT s.student_id, s.name, s.course_id, c.course_name
FROM student s
LEFT JOIN course c ON s.course_id = c.id

UNION ALL

-- Lấy các môn học chưa có sinh viên nào đăng ký
SELECT s.student_id, s.name, c.id, c.course_name
FROM course c
LEFT JOIN student s ON c.id = s.course_id
WHERE s.student_id IS NULL
"""
df_full = pd.read_sql_query(sql_full, conn)
display(df_full)
print(f"Số dòng thu được: {len(df_full)}")

"""**Nhận xét FULL OUTER JOIN:**
- **Kết quả**: 11 dòng.
- **Tổng kết**: Đây là bảng đầy đủ nhất. Nó chứa cả 10 sinh viên (bao gồm cả những người chưa có môn) và thêm môn 'Tin hoc' (môn chưa có sinh viên). Không có dữ liệu nào bị bỏ sót.

### Cập nhật và Làm sạch Dữ liệu Bảng Student

1. **Loại bỏ**: Các bản ghi có `course_id` không tồn tại trong bảng `course` (ngoại trừ NULL).
2. **Cập nhật**: Điền các giá trị `course_id` đang bị thiếu bằng các ID hợp lệ từ bảng `course`.
"""

import random

# 1. Loại bỏ các bản ghi có course_id không tồn tại trong bảng course
cur.execute("""
DELETE FROM student
WHERE course_id IS NOT NULL
AND course_id NOT IN (SELECT id FROM course)
""")

# 2. Lấy danh sách ID môn học hợp lệ
cur.execute("SELECT id FROM course")
valid_course_ids = [row[0] for row in cur.fetchall()]

# 3. Tìm các sinh viên có course_id là NULL và cập nhật ngẫu nhiên
cur.execute("SELECT student_id FROM student WHERE course_id IS NULL")
students_to_update = [row[0] for row in cur.fetchall()]

for sid in students_to_update:
    new_cid = random.choice(valid_course_ids)
    cur.execute("UPDATE student SET course_id = ? WHERE student_id = ?", (new_cid, sid))

conn.commit()

print("Dữ liệu sau khi làm sạch và cập nhật:")
display(pd.read_sql_query("SELECT * FROM student", conn))

"""### Nhận xét về Output sau khi Làm sạch Dữ liệu

Dựa trên kết quả hiển thị, chúng ta có các quan sát quan trọng sau:

1. **Số lượng bản ghi thay đổi**:
    - Ban đầu bảng `student` có 10 dòng.
    - Sau khi chạy lệnh `DELETE`, các sinh viên có `course_id` là 20 và 24 (không tồn tại trong bảng `course`) đã bị loại bỏ.
    - Kết quả còn lại **6 sinh viên** hợp lệ.

2. **Xử lý giá trị NULL**:
    - Các sinh viên như **Pham Van Nam**, **Duong Huu Phuc**, và **Cao Thi Hanh** trước đó có `course_id` là NULL.
    - Hiện tại, họ đã được cập nhật ngẫu nhiên vào các môn học có ID 12 (Giai tich) hoặc 34 (Thong ke).

3. **Tính nhất quán (Data Integrity)**:
    - Tất cả `course_id` trong bảng `student` bây giờ đều đảm bảo có giá trị tương ứng trong bảng `course`.
    - Điều này giúp cho các phép `INNER JOIN` sau này sẽ không làm mất bất kỳ sinh viên nào trong danh sách 6 người này.

### a. Thống kê Tổng số sinh viên và Điểm trung bình theo lớp

Dưới đây là bảng thống kê chi tiết cho từng lớp học dựa trên dữ liệu đã được làm sạch và cập nhật.
"""

sql_stats = """
SELECT
    class,
    COUNT(student_id) AS total_students,
    ROUND(AVG(score), 2) AS average_score
FROM student
GROUP BY class
ORDER BY average_score DESC
"""
df_stats = pd.read_sql_query(sql_stats, conn)
display(df_stats)

"""### Nhận xét về Kết quả Thống kê Lớp học

Dựa trên bảng dữ liệu sau khi làm sạch (còn 6 sinh viên), chúng ta có các nhận xét sau:

1. **Phân bổ sinh viên (total_students)**:
    - **Lớp Kinh Tế** chiếm số lượng đông nhất (3 sinh viên).
    - **Lớp Máy Tính** (2 sinh viên) và **Toán Tin** (1 sinh viên) có số lượng ít hơn do một số bản ghi ban đầu đã bị xóa vì `course_id` không hợp lệ (mã 20 và 24).

2. **Điểm trung bình (average_score)**:
    - **Lớp Kinh Tế** dẫn đầu với điểm trung bình rất cao (**8.53**). Điều này dễ hiểu vì lớp này giữ được các sinh viên có điểm số tốt như Tran Thi Lan và Bui Tien Dung (cùng 9.2).
    - **Lớp Máy Tính** có điểm trung bình thấp nhất (**6.85**).
"""



"""### b & c. Thống kê theo Môn học và Phân loại Thi đua

Chúng ta sẽ kết nối bảng `student` với `course` để lấy tên môn học, sau đó tính toán điểm trung bình và phân loại theo tiêu chí:
- >= 9.0: Xuất sắc
- 6.0 - 8.9: Tốt
- < 6.0: Kém

### b. Thống kê Tổng số sinh viên và Điểm trung bình theo từng Môn học

Để thực hiện yêu cầu này, chúng ta cần kết nối bảng `course` với bảng `student`. Sử dụng `LEFT JOIN` giúp chúng ta không bỏ sót bất kỳ môn học nào trong danh mục, kể cả những môn hiện chưa có sinh viên đăng ký.
"""

sql_course_summary = """
SELECT
    c.course_name,
    COUNT(s.student_id) AS total_students,
    ROUND(AVG(s.score), 2) AS average_score
FROM course c
LEFT JOIN student s ON c.id = s.course_id
GROUP BY c.id, c.course_name
"""
df_course_summary = pd.read_sql_query(sql_course_summary, conn)
display(df_course_summary)

"""### Nhận xét (Câu b):

1. **Sự hiện diện của môn học (Course Visibility)**:
    - Nhìn vào kết quả, môn **Tin học** vẫn xuất hiện với `total_students` là 0.
    - **Ý nghĩa**: Điều này chứng minh rằng `LEFT JOIN` hoạt động chính xác bằng cách giữ lại toàn bộ dòng từ bảng bên trái (`course`), giúp nhà quản lý biết môn nào đang trống.

2. **Giá trị trung bình (Average Score)**:
    - Môn nào có sinh viên sẽ hiển thị điểm trung bình được làm tròn 2 chữ số.
    - Môn không có sinh viên (Tin học) sẽ có giá trị `None` hoặc `NaN` ở cột điểm trung bình. Đây không phải lỗi mà là phản ánh đúng thực tế dữ liệu không có sẵn để tính toán.

3. **Phân bổ học lực**:
    - Dựa vào kết quả, chúng ta có thể so sánh trực quan môn học nào đang có lượng sinh viên tập trung đông nhất và môn nào đang có phổ điểm cao nhất.

### c. Phân loại thi đua theo số điểm của từng môn học

Dựa trên điểm trung bình của từng môn học, chúng ta thực hiện phân loại theo tiêu chí:
- **Xuất sắc**: Điểm TB ≥ 9.0
- **Tốt**: 6.0 ≤ Điểm TB ≤ 8.9
- **Kém**: Điểm TB < 6.0
"""

sql_classification = """
SELECT
    c.course_name,
    ROUND(AVG(s.score), 2) AS average_score,
    CASE
        WHEN AVG(s.score) >= 9.0 THEN 'Xuất sắc'
        WHEN AVG(s.score) >= 6.0 THEN 'Tốt'
        ELSE 'Kém'
    END AS classification
FROM course c
LEFT JOIN student s ON c.id = s.course_id
GROUP BY c.id, c.course_name
"""
df_classification = pd.read_sql_query(sql_classification, conn)
display(df_classification)

"""### Nhận xét Kết quả Phân loại (Câu c):

1. **Phân loại Tốt**:
    - Các môn như **Giải tích** (6.95) và **Thống kê** (8.33) đều nằm trong ngưỡng từ 6.0 đến 8.9, do đó được hệ thống xếp loại **Tốt**.

2. **Phân loại Kém**:
    - Môn **Tin học** được xếp loại **Kém** vì không có sinh viên (điểm TB là NULL). Theo logic của SQL, các giá trị không xác định hoặc không đủ điểm chuẩn sẽ rơi vào nhánh `ELSE`.

### 3. Xếp hạng Sinh viên

Chúng ta sẽ sử dụng các hàm cửa sổ (Window Functions) trong SQL như `RANK()` hoặc `ROW_NUMBER()` để thực hiện xếp hạng.

### 3a. Xếp hạng theo Điểm số (Toàn trường)

Chúng ta sử dụng hàm cửa sổ `RANK()` để xếp thứ tự sinh viên dựa trên cột `score` giảm dần.
"""

sql_rank_global = """
SELECT
    name,
    class,
    score,
    RANK() OVER (ORDER BY score DESC) as rank
FROM student
ORDER BY rank ASC
"""
df_rank_global = pd.read_sql_query(sql_rank_global, conn)
print('Bảng xếp hạng sinh viên theo điểm số (Toàn trường):')
display(df_rank_global)

"""### Nhận xét về Xếp hạng theo Điểm số:

1. **Xử lý đồng hạng**: Như ta có thể thấy, **Tran Thi Lan** và **Bui Tien Dung** cùng có điểm 9.2 nên đều được xếp **hạng 1**.
2. **Khoảng cách thứ hạng**: Sau hai vị trí hạng 1, người tiếp theo (**Pham Van Nam** - 7.9) được xếp **hạng 3**. Đây là đặc trưng của hàm `RANK()`: nếu có 2 người hạng 1, vị trí hạng 2 sẽ bị bỏ qua và nhảy thẳng lên hạng 3.
3. **Phân hóa**: Bảng này cho cái nhìn tổng quan nhất về năng lực của tất cả sinh viên trong hệ thống sau khi đã làm sạch dữ liệu.

### 3b. Xếp hạng Sinh viên theo Lớp học
Sử dụng `RANK() OVER (PARTITION BY class ...)` để tính thứ hạng riêng biệt cho mỗi lớp.
"""

# 3b. Xep hang diem so sinh vien theo lop hoc
sql_rank_class = """
SELECT
    class,
    name,
    score,
    RANK() OVER (PARTITION BY class ORDER BY score DESC) as rank_in_class
FROM student
ORDER BY class, rank_in_class
"""
df_rank_class = pd.read_sql_query(sql_rank_class, conn)

print("BဂNG XဣP HကNG CHI TIဣT THEO LဣP (Cu 3b):")
display(df_rank_class)

"""### Nhận xét kết quả:
1. **Lớp Kinh Tế**: Có 2 bạn cùng hạng 1 (9.2 điểm) là Tran Thi Lan và Bui Tien Dung. Người tiếp theo (7.2 điểm) sẽ giữ hạng 3.
2. **Lớp Máy Tính**: Cao Thi Hanh hạng 1 (7.0) và Nguyen Minh Hoang hạng 2 (6.7).
3. **Lớp Toán Tin**: Pham Van Nam hạng 1 với 7.9 điểm.
"""

import pandas as pd

# 3c. Xếp hạng theo mã môn học
sql_rank_course = """
SELECT
    c.id AS course_id,
    c.course_name,
    s.name,
    s.score,
    RANK() OVER (PARTITION BY c.id ORDER BY s.score DESC) as rank_desc,
    RANK() OVER (PARTITION BY c.id ORDER BY s.score ASC) as rank_asc
FROM student s
JOIN course c ON s.course_id = c.id
"""
df_rank_course = pd.read_sql_query(sql_rank_course, conn)

print("BẢNG XẾP HẠNG CHI TIẾT THEO MÔN HỌC:")
display(df_rank_course)

# Lọc Top 3 cao nhất và thấp nhất theo từng môn
print("\n--- TOP 3 SINH VIÊN ĐIỂM CAO NHẤT THEO MÔN ---")
top_3_high = df_rank_course[df_rank_course['rank_desc'] <= 3].sort_values(['course_id', 'rank_desc'])
display(top_3_high)

print("\n--- TOP 3 SINH VIÊN ĐIỂM THẤP NHẤT THEO MÔN ---")
top_3_low = df_rank_course[df_rank_course['rank_asc'] <= 3].sort_values(['course_id', 'rank_asc'])
display(top_3_low)

"""### Nhận xét chi tiết Top 3 theo môn học:

1. **Về Top 3 cao nhất**:
    - Ở môn **Thống kê (ID 34)**: Hai bạn **Tran Thi Lan** và **Bui Tien Dung** cùng dẫn đầu với 9.2 điểm. Bạn **Duong Huu Phuc** đứng thứ 3 với 7.2 điểm.
    - Ở môn **Giải tích (ID 12)**: **Pham Van Nam** (7.9) và **Nguyen Minh Hoang** (6.7) chiếm các vị trí đầu.

2. **Về Top 3 thấp nhất**:
    - Môn **Thống kê**: **Duong Huu Phuc** (7.2) là người có điểm thấp nhất (Hạng 1 từ dưới lên).
    - Môn **Tin học (ID 26)**: Chỉ có 1 sinh viên là **Cao Thi Hanh** nên bạn này vừa là Top cao nhất vừa là Top thấp nhất của môn đó.
"""

import sqlite3
import pandas as pd

# 1. Thêm cột graduation_date (nếu chưa có)
try:
    cur.execute("ALTER TABLE student ADD COLUMN graduation_date DATETIME")
except:
    pass

# 2. Cập nhật ngày tốt nghiệp: Ngày hiện tại + số ngày tương ứng với Thứ hạng
# Sử dụng CTE để tính Rank và Update đồng nhất
sql_final_update = """
WITH student_ranks AS (
    SELECT
        student_id,
        RANK() OVER (ORDER BY score DESC) as student_rank
    FROM student
)
UPDATE student
SET graduation_date = datetime('now', 'localtime', '+' || (SELECT student_rank FROM student_ranks WHERE student_ranks.student_id = student.student_id) || ' days')
"""
cur.execute(sql_final_update)
conn.commit()

# 3. Hiển thị kết quả chi tiết
print("BẢNG CHI TIẾT NGÀY TỐT NGHIỆP DỰA TRÊN THỨ HẠNG:")
query_result = """
SELECT
    name,
    score,
    RANK() OVER (ORDER BY score DESC) as rank,
    graduation_date
FROM student
ORDER BY rank ASC
"""
df_grad = pd.read_sql_query(query_result, conn)
display(df_grad)

"""### Nhận xét chi tiết về Output:

1. **Tính chính xác của Thứ hạng (Rank)**:
    - **Đồng hạng 1**: Tran Thi Lan và Bui Tien Dung đều có 9.2 điểm, nên cột `rank` hiển thị giá trị **1**.
    - **Nhảy hạng**: Sau hai vị trí hạng 1, Pham Van Nam (7.9 điểm) được xếp thẳng vào **hạng 3**. Đây là logic đúng của hàm `RANK()`.

2. **Logic cộng ngày (Graduation Date)**:
    - Hai sinh viên **hạng 1** có `graduation_date` giống hệt nhau (Thời gian hiện tại + **1 ngày**).
    - Sinh viên **hạng 3** (Pham Van Nam) có ngày tốt nghiệp là Thời gian hiện tại + **3 ngày**.
    - Sinh viên **hạng 6** (Nguyen Minh Hoang - 6.7 điểm) có ngày tốt nghiệp xa nhất, cộng thêm **6 ngày** so với hiện tại.

3. **Định dạng dữ liệu**:
    - Cột `graduation_date` hiển thị đầy đủ Năm-Tháng-Ngày và Giờ-Phút-Giây, đảm bảo tính chuyên nghiệp cho quản lý dữ liệu đào tạo.

4. **Kết luận**:
    - Output cho thấy một sự phân hóa rõ rệt: Điểm số càng cao -> Thứ hạng càng thấp (số nhỏ) -> Thời gian chờ tốt nghiệp càng ngắn. Hệ thống đã tự động hóa hoàn toàn việc lập lịch tốt nghiệp dựa trên năng lực.
"""
