**BÀI TẬP CHƯƠNG 2 - Môn HỌC: SQL CHO KHDL**

**23174600096_Nguyễn Thành Đạt_DHKL17A2HN**

* Cho hai bảng student(student_id, name, class, course_id, score) và course(id,
course_name) như sau.
* Sử dụng jupyter notebook để chạy code, hiển thị kết quả thu được và đưa ra kết luận/
câu trả lời về kết quả cuối cùng thu được.


In [1]:
import sqlite3
import pandas as pd
from IPython.display import display

### Kết nối đến SQLite và tạo bảng student và bảng course

In [2]:
# Kết nối đến SQLite
conn = sqlite3.connect("students.db")
cursor = conn.cursor()

### Xóa bảng cũ nếu đã tồn tại

In [3]:
cursor.execute("DROP TABLE IF EXISTS student;")
cursor.execute("DROP TABLE IF EXISTS course;")
conn.commit()

### Tạo bảng student và course

In [4]:
# Tạo bảng student
cursor.execute("""
CREATE TABLE student (
    student_id INTEGER PRIMARY KEY,
    name TEXT,
    class TEXT,
    course_id INTEGER,
    score REAL
);
""")

# Tạo bảng course
cursor.execute("""
CREATE TABLE course (
    id INTEGER PRIMARY KEY,
    course_name TEXT
);
""")

conn.commit()

### Chèn dữ liệu vào bảng

In [5]:
# Dữ liệu bảng student
student_data = [
    (1, "Nguyen Minh Hoang", "May Tinh", 12, 6.7),
    (2, "Tran Thi Lan", "Kinh Te", 34, 9.2),
    (3, "Pham Van Nam", "Toan Tin", None, 7.9),
    (4, "Le Thanh Huyen", "Toan Tin", 20, 7.2),
    (5, "Vu Quoc Anh", "May Tinh", 24, 8.0),
    (6, "Dang Thuy Linh", "May Tinh", 24, 5.5),
    (7, "Bui Tien Dung", "Kinh Te", 34, 9.2),
    (8, "Ho Ngoc Mai", "Toan Tin", 20, 8.8),
    (9, "Duong Huu Phuc", "Kinh Te", None, 7.2),
    (10, "Cao Thi Hanh", "May Tinh", None, 7.0)]

# Dữ liệu bảng course
course_data = [
    (12, "Giai tich"),
    (34, "Thong ke"),
    (26, "Tin hoc")]

# Chèn dữ liệu vào bảng student
cursor.executemany(
    "INSERT INTO student (student_id, name, class, course_id, score) VALUES (?, ?, ?, ?, ?);",
    student_data)

# Chèn dữ liệu vào bảng course
cursor.executemany(
    "INSERT INTO course (id, course_name) VALUES (?, ?);",
    course_data)
conn.commit()

### Đọc dữ liệu từ database

In [6]:
# Đọc dữ liệu từ bảng student
student_df = pd.read_sql_query("SELECT * FROM student;", conn)
print("Bảng Student:")
display(student_df)

# Đọc dữ liệu từ bảng course
course_df = pd.read_sql_query("SELECT * FROM course;", conn)
print("Bảng Course:")
display(course_df)

Bảng Student:


,student_id,name,class,course_id,score
0,1,Nguyen Minh Hoang,May Tinh,12.0,6.7
1,2,Tran Thi Lan,Kinh Te,34.0,9.2
2,3,Pham Van Nam,Toan Tin,NaN,7.9
3,4,Le Thanh Huyen,Toan Tin,20.0,7.2
4,5,Vu Quoc Anh,May Tinh,24.0,8.0
5,6,Dang Thuy Linh,May Tinh,24.0,5.5
6,7,Bui Tien Dung,Kinh Te,34.0,9.2
7,8,Ho Ngoc Mai,Toan Tin,20.0,8.8
8,9,Duong Huu Phuc,Kinh Te,NaN,7.2
9,10,Cao Thi Hanh,May Tinh,NaN,7.0


Bảng Course:


,id,course_name
0,12,Giai tich
1,26,Tin hoc
2,34,Thong ke


Nhận xét:

Trong bảng student:

* Có 10 dòng, 5 cột gồm: student_id, name, class, course_id, score.
* student_id là khóa chính, kiểu số nguyên.
* name và class là kiểu chuỗi.
* course_id được khai báo là kiểu số nguyên trong SQLite, nhưng khi hiển thị bằng pandas có thể xuất hiện dạng số thực (12.0, 34.0) do cột này có giá trị thiếu (NaN).
* score là kiểu số thực.
* Các sinh viên có student_id 3, 9, 10 đang bị thiếu course_id.
* Các giá trị course_id = 20 và 24 là không hợp lệ vì không tồn tại trong bảng course.

Trong bảng course:

* Có 3 bản ghi, 2 thuộc tính gồm: id, course_name.
* id là mã môn học, course_name là tên môn học.
* Các mã môn hiện có là: 12, 26, 34.

## **Câu 1. Hãy kết nối hai bảng trên theo những cách sau:**
**- Sử dụng tích Decartes.**
**- Sử dụng JOIN: INNER JOIN, LEFT JOIN, RIGHT JOIN, FULL OUTER JOIN.**

### 1.1. Sử dụng tích Descartes

In [7]:
print("TÍCH DESCARTES:")

query_descartes = """
SELECT
    s.student_id,
    s.name,
    s.class,
    s.course_id,
    s.score,
    c.id,
    c.course_name
FROM student s, course c;
"""

df_descartes = pd.read_sql_query(query_descartes, conn)
display(df_descartes)

print(f"Số dòng kết quả: {len(df_descartes)}")

TÍCH DESCARTES:


,student_id,name,class,course_id,score,id,course_name
0,1,Nguyen Minh Hoang,May Tinh,12.0,6.7,12,Giai tich
1,1,Nguyen Minh Hoang,May Tinh,12.0,6.7,26,Tin hoc
2,1,Nguyen Minh Hoang,May Tinh,12.0,6.7,34,Thong ke
3,2,Tran Thi Lan,Kinh Te,34.0,9.2,12,Giai tich
4,2,Tran Thi Lan,Kinh Te,34.0,9.2,26,Tin hoc
5,2,Tran Thi Lan,Kinh Te,34.0,9.2,34,Thong ke
6,3,Pham Van Nam,Toan Tin,NaN,7.9,12,Giai tich
7,3,Pham Van Nam,Toan Tin,NaN,7.9,26,Tin hoc
8,3,Pham Van Nam,Toan Tin,NaN,7.9,34,Thong ke
9,4,Le Thanh Huyen,Toan Tin,20.0,7.2,12,Giai tich


Số dòng kết quả: 30


Kết luận:
* Tích Descartes ghép mỗi sinh viên với tất cả các môn học trong bảng course.
* Vì bảng student có 10 dòng và bảng course có 3 dòng nên kết quả có 10 x 3 = 30 dòng.
* Kết quả này không phản ánh đúng quan hệ đăng ký môn học thực tế, mà chỉ minh họa phép kết hợp mọi khả năng giữa hai bảng.
* Các sinh viên có course_id bị thiếu vẫn xuất hiện bình thường vì phép tích Descartes không cần điều kiện nối.

### 1.2. INNER JOIN

In [8]:
print("INNER JOIN:")

query_inner = """
SELECT
    s.student_id,
    s.name,
    s.class,
    s.course_id,
    s.score,
    c.id,
    c.course_name
FROM student s
INNER JOIN course c
    ON s.course_id = c.id;
"""

df_inner = pd.read_sql_query(query_inner, conn)
display(df_inner)

print(f"Số dòng kết quả: {len(df_inner)}")

INNER JOIN:


,student_id,name,class,course_id,score,id,course_name
0,1,Nguyen Minh Hoang,May Tinh,12,6.7,12,Giai tich
1,2,Tran Thi Lan,Kinh Te,34,9.2,34,Thong ke
2,7,Bui Tien Dung,Kinh Te,34,9.2,34,Thong ke


Số dòng kết quả: 3


Kết luận:
* INNER JOIN chỉ lấy các dòng có course_id trong bảng student khớp với id trong bảng course.
* Với dữ liệu hiện tại chỉ có các mã môn hợp lệ là 12 và 34 xuất hiện trong bảng student.
* Kết quả chỉ còn 3 sinh viên có mã môn hợp lệ:
  * Nguyễn Minh Hoàng (12)
  * Trần Thị Lan (34)
  * Bùi Tiến Dũng (34)
* Các dòng có course_id bị thiếu hoặc có giá trị không tồn tại trong course như 20, 24 đều không xuất hiện.

### 1.3. LEFT JOIN

In [9]:
print("LEFT JOIN:")

query_left = """
SELECT
    s.student_id,
    s.name,
    s.class,
    s.course_id,
    s.score,
    c.id,
    c.course_name
FROM student s
LEFT JOIN course c
    ON s.course_id = c.id;
"""

df_left = pd.read_sql_query(query_left, conn)
display(df_left)

print(f"Số dòng kết quả: {len(df_left)}")

LEFT JOIN:


,student_id,name,class,course_id,score,id,course_name
0,1,Nguyen Minh Hoang,May Tinh,12.0,6.7,12.0,Giai tich
1,2,Tran Thi Lan,Kinh Te,34.0,9.2,34.0,Thong ke
2,3,Pham Van Nam,Toan Tin,NaN,7.9,NaN,None
3,4,Le Thanh Huyen,Toan Tin,20.0,7.2,NaN,None
4,5,Vu Quoc Anh,May Tinh,24.0,8.0,NaN,None
5,6,Dang Thuy Linh,May Tinh,24.0,5.5,NaN,None
6,7,Bui Tien Dung,Kinh Te,34.0,9.2,34.0,Thong ke
7,8,Ho Ngoc Mai,Toan Tin,20.0,8.8,NaN,None
8,9,Duong Huu Phuc,Kinh Te,NaN,7.2,NaN,None
9,10,Cao Thi Hanh,May Tinh,NaN,7.0,NaN,None


Số dòng kết quả: 10


Kết luận:
* LEFT JOIN giữ lại toàn bộ dữ liệu của bảng student.
* Nếu course_id khớp với id trong bảng course thì sẽ lấy thêm course_name.
* Nếu không khớp thì các cột từ bảng course sẽ là NULL/NaN.
* Kết quả cho thấy:
  * Sinh viên có course_id = 12, 34 được ghép đúng môn học
  * Sinh viên có course_id = 20, 24 hoặc NULL không có thông tin môn học tương ứng

### 1.4. RIGHT JOIN trong SQLite

SQLite không hỗ trợ RIGHT JOIN trực tiếp trong nhiều cách làm cơ bản của môn học, nên em làm bằng cách đổi vị trí hai bảng và dùng LEFT JOIN.

In [10]:
print("RIGHT JOIN:")

query_right = """
SELECT
    c.id,
    c.course_name,
    s.student_id,
    s.name,
    s.class,
    s.course_id,
    s.score
FROM course c
LEFT JOIN student s
    ON c.id = s.course_id;
"""

df_right = pd.read_sql_query(query_right, conn)
display(df_right)

print(f"Số dòng kết quả: {len(df_right)}")

RIGHT JOIN:


,id,course_name,student_id,name,class,course_id,score
0,12,Giai tich,1.0,Nguyen Minh Hoang,May Tinh,12.0,6.7
1,26,Tin hoc,NaN,None,None,NaN,NaN
2,34,Thong ke,7.0,Bui Tien Dung,Kinh Te,34.0,9.2
3,34,Thong ke,2.0,Tran Thi Lan,Kinh Te,34.0,9.2


Số dòng kết quả: 4


Kết luận:
* RIGHT JOIN có ý nghĩa là giữ lại toàn bộ dữ liệu của bảng bên phải trong câu student RIGHT JOIN course.
* Vì SQLite không làm trực tiếp, ta đổi thành: course LEFT JOIN student
* Kết quả giữ lại toàn bộ các môn học trong bảng course.
* Môn Tin hoc có mã 26 vẫn xuất hiện dù chưa có sinh viên nào đăng ký.
* Những dòng không có sinh viên khớp sẽ có các cột phía student bằng NULL/NaN.

### 1.5. FULL OUTER JOIN trong SQLite

SQLite cũng không hỗ trợ FULL OUTER JOIN trực tiếp, nên em làm bằng cách lấy hợp của LEFT JOIN và phần còn lại từ phía bảng course.

In [11]:
print("FULL OUTER JOIN:")

query_full = """
SELECT
    s.student_id,
    s.name,
    s.class,
    s.course_id,
    s.score,
    c.id,
    c.course_name
FROM student s
LEFT JOIN course c
    ON s.course_id = c.id

UNION

SELECT
    s.student_id,
    s.name,
    s.class,
    s.course_id,
    s.score,
    c.id,
    c.course_name
FROM course c
LEFT JOIN student s
    ON c.id = s.course_id
WHERE s.student_id IS NULL;
"""

df_full = pd.read_sql_query(query_full, conn)
display(df_full)

print(f"Số dòng kết quả: {len(df_full)}")

FULL OUTER JOIN:


,student_id,name,class,course_id,score,id,course_name
0,NaN,None,None,NaN,NaN,26.0,Tin hoc
1,1.0,Nguyen Minh Hoang,May Tinh,12.0,6.7,12.0,Giai tich
2,2.0,Tran Thi Lan,Kinh Te,34.0,9.2,34.0,Thong ke
3,3.0,Pham Van Nam,Toan Tin,NaN,7.9,NaN,None
4,4.0,Le Thanh Huyen,Toan Tin,20.0,7.2,NaN,None
5,5.0,Vu Quoc Anh,May Tinh,24.0,8.0,NaN,None
6,6.0,Dang Thuy Linh,May Tinh,24.0,5.5,NaN,None
7,7.0,Bui Tien Dung,Kinh Te,34.0,9.2,34.0,Thong ke
8,8.0,Ho Ngoc Mai,Toan Tin,20.0,8.8,NaN,None
9,9.0,Duong Huu Phuc,Kinh Te,NaN,7.2,NaN,None


Số dòng kết quả: 11


Kết luận:
* FULL OUTER JOIN giữ lại toàn bộ dữ liệu của cả hai bảng.
* Các dòng khớp nhau sẽ ghép lại thành một dòng.
* Các dòng không khớp từ bảng student hoặc course vẫn được giữ lại.
* Trong kết quả:
  * Các sinh viên có course_id không hợp lệ hoặc bị thiếu vẫn xuất hiện
  * Môn Tin hoc (id = 26) cũng xuất hiện dù chưa có sinh viên đăng ký

## **2. Hãy cập nhật những giá trị course_id còn thiếu trong bảng student bằng câu lệnh SQL, trong đó các giá trị được điền là những giá trị nằm trong bảng course và loại bỏ những bản ghi tham gia những môn học không tồn tại bảng course. Sau đó hãy cho biết:**

**a. Tổng số sinh viên, điểm trung bình của từng lớp.**

**b. Tổng số sinh viên, điểm trung bình của từng môn học.**

**c. Phân loại thi đua theo số điểm của từng môn học biết:**

**-   i. Điểm TB ≥  9.0: Xuất sắc.**
**-   ii. 6.0 ≤ Điểm TB ≤ 8.9: Tốt.**
**-  iii. Điểm TB < 6.0: Kém.**

### 2.1. Cập nhật course_id còn thiếu và xóa các bản ghi không hợp lệ

In [12]:
print("Cập nhật course_id còn thiếu và xóa dữ liệu không hợp lệ")

# Cập nhật các giá trị course_id bị thiếu thành một mã môn hợp lệ trong bảng course
cursor.execute("""
UPDATE student
SET course_id = 26
WHERE course_id IS NULL;
""")

# Xóa các bản ghi có course_id không tồn tại trong bảng course
cursor.execute("""
DELETE FROM student
WHERE course_id NOT IN (SELECT id FROM course);
""")

conn.commit()

# Kiểm tra lại dữ liệu sau cập nhật
query_check = """
SELECT *
FROM student;
"""

student_updated_df = pd.read_sql_query(query_check, conn)
display(student_updated_df)

Cập nhật course_id còn thiếu và xóa dữ liệu không hợp lệ


,student_id,name,class,course_id,score
0,1,Nguyen Minh Hoang,May Tinh,12,6.7
1,2,Tran Thi Lan,Kinh Te,34,9.2
2,3,Pham Van Nam,Toan Tin,26,7.9
3,7,Bui Tien Dung,Kinh Te,34,9.2
4,9,Duong Huu Phuc,Kinh Te,26,7.2
5,10,Cao Thi Hanh,May Tinh,26,7.0


Kết luận:
* Các giá trị course_id bị thiếu đã được cập nhật thành 26, là mã môn hợp lệ có trong bảng course.
* Các bản ghi có course_id không tồn tại trong bảng course đã bị xóa.

### 2.2. Tổng số sinh viên và điểm trung bình của từng lớp

In [13]:
print("Tổng số sinh viên và điểm trung bình của từng lớp:")

query_class = """
SELECT
    class,
    COUNT(student_id) AS total_students,
    ROUND(AVG(score), 2) AS avg_score
FROM student
GROUP BY class;
"""

df_class = pd.read_sql_query(query_class, conn)
display(df_class)

Tổng số sinh viên và điểm trung bình của từng lớp:


,class,total_students,avg_score
0,Kinh Te,3,8.53
1,May Tinh,2,6.85
2,Toan Tin,1,7.90


Kết luận:
* Kinh Te có điểm trung bình cao nhất.
* May Tinh có điểm trung bình thấp hơn, cần cải thiện thêm.
* Toan Tin có ít sinh viên sau khi làm sạch dữ liệu nên kết quả trung bình có thể ít đại diện hơn.

### 2.3. Tổng số sinh viên và điểm trung bình của từng môn học

In [14]:
print("Tổng số sinh viên và điểm trung bình của từng môn học:")

query_course = """
SELECT
    course.course_name,
    COUNT(student.student_id) AS total_students,
    ROUND(AVG(student.score), 2) AS avg_score
FROM student
LEFT JOIN course
    ON student.course_id = course.id
GROUP BY course.course_name;
"""

df_course = pd.read_sql_query(query_course, conn)
display(df_course)

Tổng số sinh viên và điểm trung bình của từng môn học:


,course_name,total_students,avg_score
0,Giai tich,1,6.70
1,Thong ke,2,9.20
2,Tin hoc,3,7.37


Kết luận:
* Thong ke có điểm trung bình cao nhất.
* Giai tich có số lượng sinh viên ít và điểm trung bình chưa cao.
* Tin hoc có số lượng sinh viên nhiều hơn nhưng điểm trung bình ở mức khá.

### 2.4. Phân loại thi đua theo điểm trung bình của từng môn học

In [15]:
print("Phân loại thi đua theo điểm trung bình của từng môn học:")

query_rating = """
SELECT
    course.course_name,
    ROUND(AVG(student.score), 2) AS avg_score,
    CASE
        WHEN AVG(student.score) >= 9.0 THEN 'Xuất sắc'
        WHEN AVG(student.score) BETWEEN 6.0 AND 8.9 THEN 'Tốt'
        ELSE 'Kém'
    END AS rating
FROM student
LEFT JOIN course
    ON student.course_id = course.id
GROUP BY course.course_name;
"""

df_rating = pd.read_sql_query(query_rating, conn)
display(df_rating)

Phân loại thi đua theo điểm trung bình của từng môn học:


,course_name,avg_score,rating
0,Giai tich,6.70,Tốt
1,Thong ke,9.20,Xuất sắc
2,Tin hoc,7.37,Tốt


Kết luận:
* Môn có điểm trung bình từ 9.0 trở lên được xếp loại Xuất sắc.
* Môn có điểm trung bình từ 6.0 đến 8.9 được xếp loại Tốt.
* Môn có điểm trung bình dưới 6.0 được xếp loại Kém.
* Với dữ liệu hiện tại, Thong ke thuộc nhóm Xuất sắc, còn Giai tich và Tin hoc thuộc nhóm Tốt.

## Câu 3. Hãy xếp hạng sinh viên thông qua:

### a. Xếp hạng theo điểm số toàn bộ

In [16]:
print("Xếp hạng sinh viên theo điểm số toàn bộ:")

query_score_rank = """
SELECT
    student_id,
    name,
    class,
    course_id,
    score,
    RANK() OVER (ORDER BY score DESC) AS score_rank
FROM student
ORDER BY score DESC;
"""

df_score_rank = pd.read_sql_query(query_score_rank, conn)
display(df_score_rank)

Xếp hạng sinh viên theo điểm số toàn bộ:


,student_id,name,class,course_id,score,score_rank
0,2,Tran Thi Lan,Kinh Te,34,9.2,1
1,7,Bui Tien Dung,Kinh Te,34,9.2,1
2,3,Pham Van Nam,Toan Tin,26,7.9,3
3,9,Duong Huu Phuc,Kinh Te,26,7.2,4
4,10,Cao Thi Hanh,May Tinh,26,7.0,5
5,1,Nguyen Minh Hoang,May Tinh,12,6.7,6


Kết luận:
* Hai sinh viên Trần Thị Lan và Bùi Tiến Dũng cùng đạt 9.2 điểm nên đồng hạng 1.
* Phạm Văn Nam đứng hạng 3 với 7.9 điểm.
* Điểm thấp nhất thuộc về Nguyễn Minh Hoàng với 6.7 điểm.

### b. Xếp hạng theo điểm số trong từng lớp

In [17]:
print("Xếp hạng sinh viên theo điểm số trong từng lớp:")

query_class_rank = """
SELECT
    student_id,
    name,
    class,
    course_id,
    score,
    RANK() OVER (PARTITION BY class ORDER BY score DESC) AS class_rank
FROM student
ORDER BY class, class_rank;
"""

df_class_rank = pd.read_sql_query(query_class_rank, conn)
display(df_class_rank)

Xếp hạng sinh viên theo điểm số trong từng lớp:


,student_id,name,class,course_id,score,class_rank
0,2,Tran Thi Lan,Kinh Te,34,9.2,1
1,7,Bui Tien Dung,Kinh Te,34,9.2,1
2,9,Duong Huu Phuc,Kinh Te,26,7.2,3
3,10,Cao Thi Hanh,May Tinh,26,7.0,1
4,1,Nguyen Minh Hoang,May Tinh,12,6.7,2
5,3,Pham Van Nam,Toan Tin,26,7.9,1


Kết luận:
* Trong lớp Kinh Te, Trần Thị Lan và Bùi Tiến Dũng cùng đứng hạng 1.
* Trong lớp May Tinh, Cao Thị Hạnh đứng hạng 1, Nguyễn Minh Hoàng đứng hạng 2.
* Trong lớp Toan Tin, chỉ có Phạm Văn Nam nên đứng hạng 1.

### c. Xếp hạng theo điểm số trong từng mã môn học

In [18]:
print("Xếp hạng sinh viên theo điểm số trong từng mã môn học:")

query_course_rank = """
SELECT
    student_id,
    name,
    class,
    course_id,
    score,
    RANK() OVER (PARTITION BY course_id ORDER BY score DESC) AS course_rank
FROM student
ORDER BY course_id, course_rank;
"""

df_course_rank = pd.read_sql_query(query_course_rank, conn)
display(df_course_rank)

Xếp hạng sinh viên theo điểm số trong từng mã môn học:


,student_id,name,class,course_id,score,course_rank
0,1,Nguyen Minh Hoang,May Tinh,12,6.7,1
1,3,Pham Van Nam,Toan Tin,26,7.9,1
2,9,Duong Huu Phuc,Kinh Te,26,7.2,2
3,10,Cao Thi Hanh,May Tinh,26,7.0,3
4,2,Tran Thi Lan,Kinh Te,34,9.2,1
5,7,Bui Tien Dung,Kinh Te,34,9.2,1


Kết luận:
* Môn 12 chỉ có Nguyễn Minh Hoàng nên đứng hạng 1.
* Môn 26 có Phạm Văn Nam đứng đầu với 7.9, tiếp theo là Dương Hữu Phúc và Cao Thị Hạnh.
* Môn 34 có Trần Thị Lan và Bùi Tiến Dũng cùng đứng hạng 1.

## Top 3 cao nhất và top 3 thấp nhất

### a. Top 3 cao nhất và thấp nhất theo điểm số toàn bộ

In [19]:
print("Top 3 cao nhất và thấp nhất theo điểm số toàn bộ:")

query_top_score = """
WITH ranked_students AS (
    SELECT
        student_id,
        name,
        class,
        course_id,
        score,
        RANK() OVER (ORDER BY score DESC) AS rank_high,
        RANK() OVER (ORDER BY score ASC) AS rank_low
    FROM student
)
SELECT *
FROM ranked_students
WHERE rank_high <= 3 OR rank_low <= 3
ORDER BY score DESC;
"""

df_top_score = pd.read_sql_query(query_top_score, conn)
display(df_top_score)

Top 3 cao nhất và thấp nhất theo điểm số toàn bộ:


,student_id,name,class,course_id,score,rank_high,rank_low
0,2,Tran Thi Lan,Kinh Te,34,9.2,1,5
1,7,Bui Tien Dung,Kinh Te,34,9.2,1,5
2,3,Pham Van Nam,Toan Tin,26,7.9,3,4
3,9,Duong Huu Phuc,Kinh Te,26,7.2,4,3
4,10,Cao Thi Hanh,May Tinh,26,7.0,5,2
5,1,Nguyen Minh Hoang,May Tinh,12,6.7,6,1


Nhận xét:
* Top cao nhất:
  * Trần Thị Lan: 9.2 điểm, hạng 1
  * Bùi Tiến Dũng: 9.2 điểm, hạng 1
  * Phạm Văn Nam: 7.9 điểm, hạng 3
* Top thấp nhất:
  * Nguyễn Minh Hoàng: 6.7 điểm
  * Cao Thị Hạnh: 7.0 điểm
  * Dương Hữu Phúc: 7.2 điểm

### b. Top 3 cao nhất và thấp nhất theo từng lớp

In [20]:
print("Top 3 cao nhất và thấp nhất theo từng lớp:")

query_top_class = """
WITH ranked_students AS (
    SELECT
        student_id,
        name,
        class,
        course_id,
        score,
        RANK() OVER (PARTITION BY class ORDER BY score DESC) AS rank_high,
        RANK() OVER (PARTITION BY class ORDER BY score ASC) AS rank_low
    FROM student
)
SELECT *
FROM ranked_students
WHERE rank_high <= 3 OR rank_low <= 3
ORDER BY class, score DESC;
"""

df_top_class = pd.read_sql_query(query_top_class, conn)
display(df_top_class)

Top 3 cao nhất và thấp nhất theo từng lớp:


,student_id,name,class,course_id,score,rank_high,rank_low
0,2,Tran Thi Lan,Kinh Te,34,9.2,1,2
1,7,Bui Tien Dung,Kinh Te,34,9.2,1,2
2,9,Duong Huu Phuc,Kinh Te,26,7.2,3,1
3,10,Cao Thi Hanh,May Tinh,26,7.0,1,2
4,1,Nguyen Minh Hoang,May Tinh,12,6.7,2,1
5,3,Pham Van Nam,Toan Tin,26,7.9,1,1


Nhận xét:
* Lớp Kinh Te:
  * Cao nhất: Trần Thị Lan, Bùi Tiến Dũng (9.2)
  * Thấp nhất: Dương Hữu Phúc (7.2)
* Lớp May Tinh:
  * Cao nhất: Cao Thị Hạnh (7.0)
  * Thấp nhất: Nguyễn Minh Hoàng (6.7)
* Lớp Toan Tin:
Chỉ có Phạm Văn Nam nên vừa là cao nhất vừa là thấp nhất.

### c. Top 3 cao nhất và thấp nhất theo từng mã môn học

In [21]:
print("Top 3 cao nhất và thấp nhất theo từng mã môn học:")

query_top_course = """
WITH ranked_students AS (
    SELECT
        student_id,
        name,
        class,
        course_id,
        score,
        RANK() OVER (PARTITION BY course_id ORDER BY score DESC) AS rank_high,
        RANK() OVER (PARTITION BY course_id ORDER BY score ASC) AS rank_low
    FROM student
)
SELECT *
FROM ranked_students
WHERE rank_high <= 3 OR rank_low <= 3
ORDER BY course_id, score DESC;
"""

df_top_course = pd.read_sql_query(query_top_course, conn)
display(df_top_course)

Top 3 cao nhất và thấp nhất theo từng mã môn học:


,student_id,name,class,course_id,score,rank_high,rank_low
0,1,Nguyen Minh Hoang,May Tinh,12,6.7,1,1
1,3,Pham Van Nam,Toan Tin,26,7.9,1,3
2,9,Duong Huu Phuc,Kinh Te,26,7.2,2,2
3,10,Cao Thi Hanh,May Tinh,26,7.0,3,1
4,2,Tran Thi Lan,Kinh Te,34,9.2,1,1
5,7,Bui Tien Dung,Kinh Te,34,9.2,1,1


Nhận xét:
* Môn Giải tích:
  * Chỉ có Nguyễn Minh Hoàng nên vừa cao nhất vừa thấp nhất.
* Môn Tin học:
  * Cao nhất: Phạm Văn Nam (7.9)
  * Thấp hơn: Dương Hữu Phúc (7.2), Cao Thị Hạnh (7.0)
* Môn Thống kê:
  * Trần Thị Lan và Bùi Tiến Dũng cùng cao nhất với 9.2
  * Đồng thời cũng là thấp nhất vì chỉ có 2 sinh viên và bằng điểm nhau.

## 4. Hãy bổ sung thêm một trường graduation_date có kiểu dữ liệu là DATETIME vào bảng student để xác định thời gian tốt nghiệp của từng bạn, trong đó thời gian tốt nghiệp được xác định bởi thời gian hiện tại cộng với số hạng tương ứng của bạn đó tính theo điểm số

### 4.1. Thêm cột graduation_date vào bảng student

In [22]:
print("Thêm cột graduation_date vào bảng student")

# Kiểm tra các cột hiện có trong bảng student
columns_info = pd.read_sql_query("PRAGMA table_info(student);", conn)

if "graduation_date" not in columns_info["name"].values:
    cursor.execute("""
    ALTER TABLE student ADD COLUMN graduation_date DATETIME;
    """)
    conn.commit()
    print("Đã thêm cột graduation_date.")
else:
    print("Cột graduation_date đã tồn tại.")

Thêm cột graduation_date vào bảng student
Đã thêm cột graduation_date.


### 4.2. Cập nhật graduation_date dựa trên thứ hạng điểm số

In [23]:
print("Cập nhật graduation_date dựa trên thứ hạng điểm số")

cursor.execute("""
WITH ranked_students AS (
    SELECT
        student_id,
        RANK() OVER (ORDER BY score DESC) AS score_rank
    FROM student
)
UPDATE student
SET graduation_date = DATETIME(
    'now',
    '+' || (
        SELECT score_rank
        FROM ranked_students
        WHERE ranked_students.student_id = student.student_id
    ) || ' months'
);
""")

conn.commit()
print("Đã cập nhật graduation_date.")

Cập nhật graduation_date dựa trên thứ hạng điểm số
Đã cập nhật graduation_date.


### 4.3. Kiểm tra kết quả sau khi cập nhật

In [24]:
print("Bảng student sau khi thêm và cập nhật graduation_date:")

query_grad = """
SELECT
    student_id,
    name,
    class,
    course_id,
    score,
    graduation_date
FROM student
ORDER BY score DESC;
"""

df_grad = pd.read_sql_query(query_grad, conn)
display(df_grad)

Bảng student sau khi thêm và cập nhật graduation_date:


,student_id,name,class,course_id,score,graduation_date
0,2,Tran Thi Lan,Kinh Te,34,9.2,2026-05-03 14:17:06
1,7,Bui Tien Dung,Kinh Te,34,9.2,2026-05-03 14:17:06
2,3,Pham Van Nam,Toan Tin,26,7.9,2026-07-03 14:17:06
3,9,Duong Huu Phuc,Kinh Te,26,7.2,2026-08-03 14:17:06
4,10,Cao Thi Hanh,May Tinh,26,7.0,2026-09-03 14:17:06
5,1,Nguyen Minh Hoang,May Tinh,12,6.7,2026-10-03 14:17:06


Nhận xét:
* Sau khi thêm và cập nhật trường graduation_date, tất cả sinh viên trong bảng student đều đã có ngày tốt nghiệp dự kiến.
* Ngày tốt nghiệp được sắp theo thứ hạng điểm số: sinh viên có điểm cao hơn thì thời gian tốt nghiệp gần hơn, sinh viên có điểm thấp hơn thì thời gian tốt nghiệp xa hơn.
* Trần Thị Lan và Bùi Tiến Dũng cùng đạt 9.2 điểm nên đồng hạng 1, vì vậy có cùng graduation_date là 2026-05-03 11:17:45.
* Phạm Văn Nam đạt 7.9 điểm nên có ngày tốt nghiệp sau 2 sinh viên đứng đầu.
* Dương Hữu Phúc, Cao Thị Hạnh và Nguyễn Minh Hoàng có điểm thấp hơn nên graduation_date lần lượt muộn hơn.
* Kết quả cho thấy việc thêm cột và cập nhật dữ liệu đã thực hiện thành công, đồng thời quy tắc tính ngày tốt nghiệp theo thứ hạng được áp dụng đúng.